spring:
  application:
    name: Task Tracker
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  mail:
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com
confirmation:
  expiration:
    days: ${CONFIRMATION_EXPIRATION_DAYS}

app:
  base-url: ${BASE_URL}
  frontend-url: ${FRONTEND_URL}

digitalocean:
  spaces:
    access-key: ${DO_SPACES_ACCESS_KEY}
    secret-key: ${DO_SPACES_SECRET_KEY}
    endpoint: ${DO_SPACES_ENDPOINT}
    region: ${DO_SPACES_REGION}
    bucket-name: ${DO_SPACES_BUCKET}

jwt:
  at:
    live-in-min: ${JWT_AT_LIVE_IN_MIN}
    secret: ${JWT_AT_SECRET}
  rt:
    live-in-min: ${JWT_RT_LIVE_IN_MIN}
    secret: ${JWT_RT_SECRET}

springdoc:
  swagger-ui:
    with-credentials: true
